name: Node.js CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: Agent-1

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Frontend Compilation
        run: | 
          cd src
          find . -name "*.js" -exec node --check {} +
          
  gitleaks: 
    needs: compile
    runs-on: Agent-1
    steps:
      -  name: checkout code
         uses: actions/checkout@v4
      -  name: setup-gitleaks
         uses: gitleaks/gitleaks-action@v2

      -  name: Gitleaks-scan
         run: |
           gitleaks detect --source ./src --exit-code 1

  trivy:
    needs: gitleaks
    runs-on: Agent-1
    steps: 
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'library'
        severity: 'CRITICAL,HIGH'

  sonarqube:
    runs-on: Agent-1
    steps:
       -  name: checkout code
          uses: actions/checkout@v4
       -  name: sonarqube scan
          uses: SonarSource/sonarqube-scan-action@<action version>
          with:
            projectBaseDir: ./src
            args: >
             -Dsonar.organization=my-organization # For SonarQube Cloud only
             "-Dsonar.projectName=My Project"
             -Dsonar.projectKey=my-projectkey
             -Dsonar.sources= .
             -Dsonar.test.exclusions= **/node_modules/**,**/dist/**,**/build/**
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}   
   


        
        # trivy-config: trivy.yaml
          
      #     cache: 'npm'
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
